config/routes.rb
Rails.application.routes.draw do
  resources :news, only: %i[index show]
  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  #scope module: 'admin' do
  #  resources :news
  #end

  root 'home_page#index'
  #root 'home#home_page'

  namespace :admin do
    resources :news
    get 'update_news_list', action: :update_news_list, controller: 'news'
  end

  
  get 'index', action: :index, controller: 'home_page'
  post 'search', action: :search, controller: 'home_page'
  
  get 'weather', action: :weather, controller: 'home_page'
  get 'air_quality', action: :air_quality, controller: 'home_page'

end

app/models/admin.rb
class Admin < ApplicationRecord
  has_many :news
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  Rails.logger.info("INSIDE APPLICATION RECORD");
  self.abstract_class = true

  def self.ransackable_attributes(auth_object = nil)
    column_names + _ransackers.keys
  end

  def self.ransackable_associations(auth_object = nil)
    reflect_on_all_associations.map { |a| a.name.to_s } + _ransackers.keys
  end
end

app/models/news.rb
class News < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged


  belongs_to :admin

  validates :title, presence: true, uniqueness: true
  validates :body, presence: true
  validates :source, presence: true, uniqueness: true
  validates :header, presence: true, uniqueness: true
  validates :admin, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ErrorCathing
  include Pagy::Backend
end

app/controllers/concerns/error_cathing.rb
module ErrorCathing
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound, with: :notfound

    private

    def notfound(exception)
      render file: 'public/404.html', status: :not_found, layout: false
    end
  end
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def index
    @news = News.all.where(publish: true).order(date: :desc).limit(3)
  end

  def search
    data_geo = GeocodeService.new(params[:name]).call
    @geo = ForecastConverterService.new(data_geo).convert_geolocation
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.update("search", partial: "home_page/search")
        ]
      end
    end
  end

  def weather
    merge_params
    params.merge!({ "day"=> "7" }) if params["day"].to_i == 5
    unless params[:latitude].nil? || params[:longitude].nil?
      forecast = ForecastService.new(params).call
      data_forecast = ForecastConverterService.new(forecast)
      @convert_daily = data_forecast.convert_daily_forecast
      @current = data_forecast.convert_current_forecast
    end
  end

  def air_quality
    merge_params
    params.merge!({ "day"=> "5" }) if params["day"].to_i > 5
    session.merge!({"day"=>"5"}) if params["day"].to_i > 5 || session.to_hash["day"].to_i > 5
    unless params[:latitude].nil? || params[:longitude].nil?
      air_quality = AirQualityService.new(params).call
      data_air_quality = AirConverterService.new(air_quality)
      #@convert_houlry_air = data_air_quality.convert_hourly_quality
      @current_air = data_air_quality.convert_current_air
      @daily_air = data_air_quality.convert_daily_quality
    end
  end

  private
  def merge_params
    #params.permit(:country, :latitude, :longitude, :name, :timezone, :day, :controller, :action )
    params[:latitude].gsub!(",",".") unless params[:latitude].nil?
    params[:longitude].gsub!(",",".") unless params[:longitude].nil?
    session.merge!({"country"=> params[:country],"latitude"=> params[:latitude],"longitude"=> params[:longitude], "name"=> params[:name], "timezone"=> params[:timezone], "day"=>params[:day]}) unless params[:name].nil?
    session.merge!({"country"=> nil, "name"=> nil, "latitude"=> params[:latitude],"longitude"=> params[:longitude], "timezone"=> params[:timezone], "day"=> params[:day]}) unless params[:latitude].nil? || params[:longitude].nil? || !params[:name].nil?
    params.merge!({country: session.to_hash["country"],latitude: session.to_hash["latitude"],longitude: session.to_hash["longitude"], name: session.to_hash["name"], timezone: session.to_hash["timezone"], day: session.to_hash["day"] })
  end
end

app/controllers/news_controller.rb
class NewsController < InheritedResources::Base
  #require_relative '../../lib/assets/news/parser'

  def index
    @pagy, @news = pagy(News.all.where(publish: true).order(date: :desc))
  end

  def show
    @news = News.friendly.where(publish: true).find( params[:id])
  end

  private

    def news_params
      params.require(:news).permit(:title, :body, :date, :source, :header, :image, :publish, :admin_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
  def full_title(page_title = "")
    base = "TrueMeteo"
    if page_title.present?
      "#{page_title} | #{base}"
    else
      base
    end
  end
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/home_page/_quality.html.erb
<% unless @current_air.nil?  %>
  <h4 class="text-center fw-normal mt-5">Current Air Qaulity</h4>
	<div class="container">
		<div class="row ">
			<div class="card">
				<div class="row">
					<div class="col-md-6">
						<h5 class="card-title">
							<div class="text p-2"><%= @current_air[:time] %></div>
						</h5>
						<div class="card-body">
							<div class="row p-2 border ">
								<div class="col-md-4 text-center">
								<div class="fw-medium">Air Quality Index</div>
									<div class="progress">
										<div class="progress-bar" role="progressbar" style="width: <%= @current_air[:european_aqi] %>%; background-color: <%= @current_air[:color_index]%>;" aria-valuenow="<%= @current_air[:european_aqi] %>" aria-valuemin="0" aria-valuemax="100"></div>
									</div>
								</div>
								<div class="col-md-4 text-center">
									<div class="fw-medium"><small class="text-muted"><%= @current_air[:european_aqi] %></small></div>
								</div>
								<div class="col-md-4 text-center">
									<div class="fw-medium"><%= @current_air[:index_status] %></div>
								</div>
							</div>
							<div class="row p-2 border ">
								<h6 class="card-text mt-2"><small class="text-muted"><%= @current_air[:index_desc] %></small></h6>
							</div>
						</div>
					</div>

					<div class="col-md-6">
						<div class="card-body">
							<div class="row p-2 border ">
								<div class="col-md-4 text-center">
								<div class="fw-medium">PM<small>10</small>:</div>
									<div class="progress">
										<div class="progress-bar" role="progressbar" style="width: <%= @current_air[:aqi_pm10] %>%; background-color: <%= @current_air[:color_index_aqi_pm10]%>;" aria-valuenow="<%= @current_air[:european_aqi] %>" aria-valuemin="0" aria-valuemax="100"></div>
									</div>
								</div>
								<div class="col-md-4 text-center">
									<div class="fw-medium"><small class="text-muted"><%= @current_air[:aqi_pm10] %></small></div>
									<div class="fw-medium"><small class="text-muted"><%= @current_air[:pm10] %> μg/m³</small></div>
								</div>
								<div class="col-md-4 text-center">
									<div class="fw-medium"><%= @current_air[:index_pm10] %></div>
								</div>
							</div>

							<div class="row p-2 border ">
								<div class="col-md-4 text-center">
								<div class="fw-medium">PM<small>2.5</small>:</div>
									<div class="progress">
										<div class="progress-bar" role="progressbar" style="width: <%= @current_air[:aqi_pm2_5] %>%; background-color: <%= @current_air[:color_index_aqi_pm2_5]%>;" aria-valuenow="<%= @current_air[:european_aqi] %>" aria-valuemin="0" aria-valuemax="100"></div>
									</div>
								</div>
								<div class="col-md-4 text-center">
									<div class="fw-medium"><small class="text-muted"><%= @current_air[:aqi_pm2_5] %></small></div>
									<div class="fw-medium"><small class="text-muted"><%= @current_air[:pm2_5] %> μg/m³</small></div>
								</div>
								<div class="col-md-4 text-center">
									<div class="fw-medium"><%= @current_air[:index_pm2_5] %></div>
								</div>
							</div>

							<div class="row p-2 border ">
								<div class="col-md-4 text-center">
								<div class="fw-medium">NO<small>2</small>:</div>
									<div class="progress">
										<div class="progress-bar" role="progressbar" style="width: <%= @current_air[:aqi_nitrogen_dioxide] %>%; background-color: <%= @current_air[:color_index_aqi_nitrogen_dioxide]%>;" aria-valuenow="<%= @current_air[:european_aqi] %>" aria-valuemin="0" aria-valuemax="100"></div>
									</div>
								</div>
								<div class="col-md-4 text-center">
									<div class="fw-medium"><small class="text-muted"><%= @current_air[:aqi_nitrogen_dioxide] %></small></div>
									<div class="fw-medium"><small class="text-muted"><%= @current_air[:nitrogen_dioxide] %> μg/m³</small></div>
								</div>
								<div class="col-md-4 text-center">
									<div class="fw-medium"><%= @current_air[:index_aqi_nitrogen_dioxide] %></div>
								</div>
							</div>

							<div class="row p-2 border ">
								<div class="col-md-4 text-center">
								<div class="fw-medium">SO<small>2</small>:</div>
									<div class="progress">
										<div class="progress-bar" role="progressbar" style="width: <%= @current_air[:aqi_sulphur_dioxide] %>%; background-color: <%= @current_air[:color_index_aqi_sulphur_dioxide]%>;" aria-valuenow="<%= @current_air[:european_aqi] %>" aria-valuemin="0" aria-valuemax="100"></div>
									</div>
								</div>
								<div class="col-md-4 text-center">
									<div class="fw-medium"><small class="text-muted"><%= @current_air[:aqi_sulphur_dioxide] %></small></div>
									<div class="fw-medium"><small class="text-muted"><%= @current_air[:sulphur_dioxide] %> μg/m³</small></div>
								</div>
								<div class="col-md-4 text-center">
									<div class="fw-medium"><%= @current_air[:index_aqi_sulphur_dioxide] %></div>
								</div>
							</div>

							<div class="row p-2 border ">
								<div class="col-md-4 text-center">
								<div class="fw-medium">O<small>3</small>:</div>
									<div class="progress">
										<div class="progress-bar" role="progressbar" style="width: <%= @current_air[:aqi_ozone] %>%; background-color: <%= @current_air[:color_index_aqi_ozone]%>;" aria-valuenow="<%= @current_air[:european_aqi] %>" aria-valuemin="0" aria-valuemax="100"></div>
									</div>
								</div>
								<div class="col-md-4 text-center">
									<div class="fw-medium"><small class="text-muted"><%= @current_air[:aqi_ozone] %></small></div>
									<div class="fw-medium"><small class="text-muted"><%= @current_air[:ozone] %> μg/m³</small></div>
								</div>
								<div class="col-md-4 text-center">
									<div class="fw-medium"><%= @current_air[:index_aqi_ozone] %></div>
								</div>
							</div>
								
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="container">
		<h4 class="text-center fw-normal mt-5">Daily Air Quality Forecast</h4>
		<ul class="nav nav-tabs justify-content-center" id="forecastTabs" role="tablist">
			<li class="nav-item">
				<%= link_to "3 Days", air_quality_path(day: "3", latitude: params[:latitude], longitude: params[:longitude], name: params["name"], timezone: params[:timezone], country: params[:country]), class:"nav-link #{"active" if params[:day] == "3"} link-dark", controller: "home_page", action: "air_quality" %>
			</li>
			<li class="nav-item">
				<%= link_to "5 Days", air_quality_path(day: "5", latitude: params[:latitude], longitude: params[:longitude], name: params["name"], timezone: params[:timezone], country: params[:country]), class: "nav-link #{"active" if params[:day] == "5"} link-dark", controller: "home_page", action: "air_quality" %>
			</li>
		</ul>
	</div>

	<div>
		<% @daily_air.each_slice(3).with_index do |value, index| %>
			<div class="row row-cols-3">
				<% value.each do |row| %>
					<div class="card">
						<div class="row">
							<div class="col-md-12">
								<h5 class="card-title p-2">
									<div class="nav nav-tabs justify-content-start"> 
										<div class="nav-link link-info" ><%= row[:day] %></div>
									</div>
								</h5>
								<div class="card-body">
									<div class="row p-2 border ">
										<div class="col-md-4 text-center">
										<div class="fw-medium">Air Quality</div>
											<div class="progress">
												<div class="progress-bar" role="progressbar" style="width: <%= row[:european_aqi] %>%; background-color: <%= row[:colot_index_aqi]%>;" aria-valuenow="<%= row[:european_aqi] %>" aria-valuemin="0" aria-valuemax="100"></div>
											</div>
										</div>
										<div class="col-md-4 text-center">
											<div class="fw-medium"><small class="text-muted"><%= row[:european_aqi] %></small></div>
										</div>
										<div class="col-md-4 text-center">
											<div class="fw-medium"><%= row[:index_aqi] %></div>
										</div>
									</div>

									<div class="row p-2 border ">
										<div class="col-md-4 text-center">
										<div class="fw-medium">PM<small>10</small>:</div>
											<div class="progress">
												<div class="progress-bar" role="progressbar" style="width: <%= row[:aqi_pm10] %>%; background-color: <%= row[:color_index_aqi_pm10]%>;" aria-valuenow="<%= row[:european_aqi] %>" aria-valuemin="0" aria-valuemax="100"></div>
											</div>
										</div>
										<div class="col-md-4 text-center">
											<div class="fw-medium"><small class="text-muted"><%= row[:aqi_pm10] %></small></div>
											<div class="fw-medium"><small class="text-muted">≈<%= row[:pm10] %> μg/m³</small></div>
										</div>
										<div class="col-md-4 text-center">
											<div class="fw-medium"><%= row[:index_pm10] %></div>
										</div>
									</div>

									<div class="row p-2 border ">
										<div class="col-md-4 text-center">
										<div class="fw-medium">PM<small>2.5</small>:</div>
											<div class="progress">
												<div class="progress-bar" role="progressbar" style="width: <%= row[:aqi_pm2_5] %>%; background-color: <%= row[:color_index_aqi_pm2_5]%>;" aria-valuenow="<%= row[:european_aqi] %>" aria-valuemin="0" aria-valuemax="100"></div>
											</div>
										</div>
										<div class="col-md-4 text-center">
											<div class="fw-medium"><small class="text-muted"><%= row[:aqi_pm2_5] %></small></div>
											<div class="fw-medium"><small class="text-muted">≈<%= row[:pm2_5] %> μg/m³</small></div>
										</div>
										<div class="col-md-4 text-center">
											<div class="fw-medium"><%= row[:index_pm2_5] %></div>
										</div>
									</div>

									<div class="row p-2 border ">
										<div class="col-md-4 text-center">
										<div class="fw-medium">NO<small>2</small>:</div>
											<div class="progress">
												<div class="progress-bar" role="progressbar" style="width: <%= row[:aqi_nitrogen_dioxide] %>%; background-color: <%= row[:color_index_aqi_nitrogen_dioxide]%>;" aria-valuenow="<%= row[:european_aqi] %>" aria-valuemin="0" aria-valuemax="100"></div>
											</div>
										</div>
										<div class="col-md-4 text-center">
											<div class="fw-medium"><small class="text-muted"><%= row[:aqi_nitrogen_dioxide] %></small></div>
											<div class="fw-medium"><small class="text-muted">≈<%= row[:nitrogen_dioxide] %> μg/m³</small></div>
										</div>
										<div class="col-md-4 text-center">
											<div class="fw-medium"><%= row[:index_aqi_nitrogen_dioxide] %></div>
										</div>
									</div>

									<div class="row p-2 border ">
										<div class="col-md-4 text-center">
										<div class="fw-medium">SO<small>2</small>:</div>
											<div class="progress">
												<div class="progress-bar" role="progressbar" style="width: <%= row[:aqi_sulphur_dioxide] %>%; background-color: <%= row[:color_index_aqi_sulphur_dioxide]%>;" aria-valuenow="<%= @current_air[:european_aqi] %>" aria-valuemin="0" aria-valuemax="100"></div>
											</div>
										</div>
										<div class="col-md-4 text-center">
											<div class="fw-medium"><small class="text-muted"><%= row[:aqi_sulphur_dioxide] %></small></div>
											<div class="fw-medium"><small class="text-muted">≈<%= row[:sulphur_dioxide] %> μg/m³</small></div>
										</div>
										<div class="col-md-4 text-center">
											<div class="fw-medium"><%= row[:index_aqi_sulphur_dioxide] %></div>
										</div>
									</div>

									<div class="row p-2 border ">
										<div class="col-md-4 text-center">
										<div class="fw-medium">O<small>3</small>:</div>
											<div class="progress">
												<div class="progress-bar" role="progressbar" style="width: <%= @current_air[:aqi_ozone] %>%; background-color: <%= @current_air[:color_index_aqi_ozone]%>;" aria-valuenow="<%= @current_air[:european_aqi] %>" aria-valuemin="0" aria-valuemax="100"></div>
											</div>
										</div>
										<div class="col-md-4 text-center">
											<div class="fw-medium"><small class="text-muted"><%= row[:aqi_ozone] %></small></div>
											<div class="fw-medium"><small class="text-muted">≈<%= row[:ozone] %> μg/m³</small></div>
										</div>
										<div class="col-md-4 text-center">
											<div class="fw-medium"><%= row[:index_aqi_ozone] %></div>
										</div>
									</div>

								</div>
							</div>
						</div>
					</div>
				<% end %>
			</div>
		<% end %>
	</div>
<% end %>

app/views/home_page/_search.html.erb
<% unless @geo.nil?  %>
  <div class="list">
    <div class= "list-group" >
      <% @geo.each do |row| %>
        <li class="list-group-item list-group-item-action">
          <div class='row'>
            <div class='col-sm-8'>
              <%= link_to row[:value],
                weather_path(latitude: row[:latitude], longitude: row[:longitude], day: "3", name: row[:value], timezone: row[:timezone], country: row[:country]),
                method: :get,
                data: {turbo: false},
                controller: "home_page",
                action: "weather"
              %>
            </div>
            <div class='col-sm-4'> <%= row[:country] %> </div>
          </div>
          <div class='row'>
            <div class='col-sm'> <%= row[:timezone] %> </div>
          </div>
        </li>
      <% end %>
    </div>
  </div>
<% end %>

app/views/home_page/air_quality.html.erb
<%= provide :page_title, "Air Quality" %>

<div class="container mt-5">
  <%= form_with url: air_quality_path, method: :get, class: "d-flex"  do |form| %>
    <%= form.search_field :latitude, class: "form-control me-2", placeholder: "Latitude:" %>
    <%= form.search_field :longitude, class: "form-control me-2", placeholder: "Longitude:" %>
    <% time_zone = ["America/Anchorage","America/Los_Angeles","America/Denver","America/Chicago","America/New_York","America/Sao_Paulo","Europe/London","Europe/Berlin","Europe/Kiev","Europe/Moscow","Africa/Cairo","Asia/Bangkok","Asia/Singapore","Asia/Tokyo","Australia/Sydney","Pacific/Auckland"] %>
    <%= form.select :timezone, time_zone.map {|el| el }, {}, class:"form-select" %>
    <%= form.submit "Search", class:"btn btn-outline-secondary btn-lg" %>
  <% end %>
</div>

<%= render partial: "quality" %>

app/views/home_page/index.html.erb
<%= provide :page_title, "Home" %>

<div>
  <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= image_tag "weather.jpg" ,class:"d-block" %>
        <div class="carousel-caption p-2 bg-body text-secondary">
          <h3>Accurate Weather Forecasts for Any Location</h3>
          <p>Seamless integration of high-resolution weather models with up 16 days forecast</p>
        </div>
      </div>
      <div class="carousel-item">
        <%= image_tag "air_quality.jpg" ,class:"d-block" %>
        <div class="carousel-caption p-2 bg-body text-secondary">
          <h3>Air Quality Forecasts</h3>
          <p>Pollutants and pollen forecast in 11 km resolution</p>
        </div>
      </div>
      <div class="carousel-item">
        <%= image_tag "news.jpg" ,class:"d-block" %>
        <div class="carousel-caption p-2 bg-body text-secondary">
          <h3>Climate News</h3>
          <p>Hear from journalists all over the world sharing their insights about covering climate change</p>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>
<h4 class="text-center fw-normal mt-5">Last Climate News</h4>
<%= render partial: "news/news" %>

app/views/home_page/weather.html.erb
<%= provide :page_title, "Weather" %>

<div class="container mt-5">
  <%= form_with url: weather_path, method: :get, class: "d-flex"  do |form| %>
    <%= form.search_field :latitude, class: "form-control me-2", placeholder: "Latitude:" %>
    <%= form.search_field :longitude, class: "form-control me-2", placeholder: "Longitude:" %>
    <% time_zone = ["America/Anchorage","America/Los_Angeles","America/Denver","America/Chicago","America/New_York","America/Sao_Paulo","Europe/London","Europe/Berlin","Europe/Kiev","Europe/Moscow","Africa/Cairo","Asia/Bangkok","Asia/Singapore","Asia/Tokyo","Australia/Sydney","Pacific/Auckland"] %>
    <%= form.select :timezone, time_zone.map {|el| el }, {}, class:"form-select" %>
    <%= form.submit "Search", class:"btn btn-outline-secondary btn-lg" %>
  <% end %>
</div>



<%= render partial: "forecast" %>

app/views/layouts/_footer.html.erb
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
	<div class="col-md-4 d-flex align-items-center">
		<span class="mb-3 mb-md-0 text-muted">© <%= Time.now.strftime("%Y")%> Link, Inc</span>
	</div>
</footer>

app/views/layouts/_nav.html.erb
<div class="sticky-top">
  <nav class="navbar navbar-expand navbar-dark bg-dark">
    <div class="container-fluid">
      <div class="navbar-brand">
        <%= image_tag "temp.png" ,class:"d-inline-block align-text-top", style: "width: 40px; height: 40px;" %>
        TrueMeteo      
      </div>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Weather", weather_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Air Quality", air_quality_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "News", news_index_path, class: "nav-link" %>
          </li>
        </ul>
        <ul class="navbar-nav me-5">
          <li class="nav-item">
            <% unless session[:country].nil? || session[:name].nil? %>
              <div class="nav-link active"><%= session[:country] %>/<%= session[:name] %></div>
            <% end %>
          </li>
        </ul>
        <div class="d-flex" >
          <%= form_with url: search_path, method: :post, class: "d-flex" ,data: {turbo_frame: "search", turbo_action: "advance", controller: "search", action: "input->search#submit"} do |form| %>
            <%= form.search_field :name , class: "form-control me-2", placeholder: "Search City"%>
            <%#= form.submit "Search", class:"btn btn-outline-secondary" %>
            <%# autocomplete: :off %>
          <% end %>
        </div>
      </div>
    </div>
  </nav>
  <%= turbo_frame_tag "search" do %>
    <%= render partial: "home_page/search" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:page_title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="container-fluid">
    <%= render partial: "layouts/nav" %>
    <div class="container">
      <%= yield %>
    </div>
    <div class="container sticky-bottom" >
      <%= render partial: "layouts/footer"%>
    </div>
  </body>
</html>

app/views/news/_news.html.erb
<div id="news" class="mt-3">
  <div class="row row-cols-3">
    <% @news.each do |news| %>
      <div class="card">
        <%= link_to(news, class:"card-link") do %>
          <div>
            <%= image_tag(news.image, class: "card-img") %>
          </div>
          <div class="card-header bg-transparent">
            <h5 class="card-title"><%= news.title %></h5>
          </div>
        <% end %>
        <div class="card-body">
          <div class="card-text">
            <%= news.header %>
          </div>
        </div>
        <div class="card-footer bg-transparent">
          <small class="text-muted"><%= news.date %></small>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/news/index.html.erb
<%= provide :page_title, "News" %>
<h4 class="text-center fw-normal mt-5">Climate News</h4>

<div class="card row">

  <%= render partial: "news/news" %>
  <div class="mt-5">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/news/show.html.erb
<%= provide :page_title, "#{@news.title}" %>
<div class="card mt-2">
  <div class="card-header bg-transparent">
    <div class="row">
      <div class="col-md-1">
        <%= link_to(:back) do %>
        <%= image_tag "left.png" ,class:"img-sm" %>
        <% end %>
      </div>
      <div class="col-md-11">
        <h4 class="card-title"><%= @news.title %></h4>
        <p class="text-muted"><%= @news.header %></p>
      </div>
    </div>
  </div>
  <div class="card-body">
    <div class="card-text">
      <p>
        <%== @news.body %>
      </p>
    </div>
  </div>
  <div class="card-footer bg-transparent">
    <small class="text-muted"><%= @news.date.strftime("%e %B %Y") %></small>
    <br>
    <%= link_to "Source: #{@news.source} ", @news.source , class:"text-muted"%>
  </div>
</div>